name = "PolyaViz"
uuid = "a7680efe-4291-11ea-33dc-a95331a1cc22"
authors = ["Michiel Van Lancker <michiel.vanlancker@cs.kuleuven.be>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
